### ISSUE TITLE
Configuration Variables

### ISSUE THREAD

**Issue by Crasho21** [alessandrolulli/reforest#2]
Which are all the configuration variables? Which are their default values?
Thank you in advance for your help.
Best regards,

Cristian

**Comment by alessandrolulli** [comment]
Dear Cristian,

detailed information about ReForeSt can be retrieved at the following website: https://sites.google.com/view/reforest

From the website there is the link to the API where on the reforest.rf.parameter package it is possible to find all the configuration variables:
http://www.alessandrolulli.com/reforest/api/current/#reforest.rf.parameter.package

However, i think such part of documentation should be improved and i am planning to add a better documentation about all the configuration variables and their details.

**Comment by Crasho21** [comment]
Dear Alessandro,

thank you for your answer, it was really helpful.

Cristian
